### ISSUE TITLE
wrong with runing with gpus 

### ISSUE THREAD

**Issue by daizhenyu** [Phoenix1327/tea-action-recognition#12]

**Comment by daizhenyu** [comment]
![Uploading image.png…]()

**Comment by daizhenyu** [comment]
![image](https://user-images.githubusercontent.com/67902793/113416163-50640400-93f3-11eb-8a6d-0ce10d99bf14.png)

**Comment by jwli6** [comment]
@daizhenyu How did you solve this problem?
